### ISSUE TITLE
It does not work with ExtJS 5

### ISSUE THREAD

**Issue by linyatis** [elmasse/Ext.i18n.Bundle#16]
I started an app with ExtJS 5 and checked that this plugin does not work on it.

First I deleted [this snippet of code][1] and it started working again.
But with json format I had issues again:
> Error: Uncaught TypeError: undefined is not a function at line 29 of Json.js:
```
record = new Model(undefined, me.getId(node), node, convertedValues = {});
```

I tried to solve this issue but failed.

Just for curiosity, I checked that it does not show any error with property format but it always shows value `my.property.undefined`.

[1]: https://github.com/elmasse/Ext.i18n.Bundle/blob/master/i18n/Bundle.js#L226-L232

**Comment by Scorpie** [comment]
@linyatis do you have that package available perhaps?

**Comment by elmasse** [comment]
@Scorpie in case @linyatis hasn't the package ready I was thinking to take a look on this over the weekend. 

I will move the code into a package structure and I will probably post the build version (.pkg) in my website so you can add the url as a sencha cmd remote repo.

But, again, if someone did already some work in this direction please feel free to send a PR!

**Comment by elmasse** [comment]
@Scorpie @linyatis 
I will update the repo soon. Meanwhile you can use the bundle as a Sencha Cmd package. Just go thru the following steps:

1. Add my repo to Sencha Cmd repo list `sencha repo add elmasse http://elmasse.github.io/cmd/pkgs`
2. Modify you app.json to include `requires: ["elmasse-bundle"]` 
3. Run `sencha app refresh` or just `sencha app watch`

**Comment by elmasse** [comment]
package code is merge into master.

**Comment by yellenseram** [comment]
The update was not available when I was using this so I changed the Json,js to this instead


------------------------------------------------------------------------------------------------------------

Ext.define('FICOCore.component.i18n.reader.Json', {
    extend: 'Ext.data.reader.Json',
    alias : 'reader.i18n.json',

    extractData: function(root, readOptions){
       var me = this,
       		entityType = readOptions && readOptions.model ? Ext.data.schema.Schema.lookupEntity(readOptions.model) : me.getModel(),
            schema = entityType.schema,
            includes = schema.hasAssociations(entityType) && me.getImplicitIncludes(),
            fieldExtractorInfo = me.getFieldExtractorInfo(entityType.fieldExtractors),
            length  = root.length,
            records = new Array(length),
            typeProperty = me.getTypeProperty(),
            reader, node, nodeType, key, value, obj,  convertedValues, record, i;
            
        if (!length && Ext.isObject(root)) {
            root = [root];
            length = 1;
        }
        
        for (i = 0; i < length; i++) {
            record = root[i];
            if (!record.isModel) {
                // If we're given a model instance in the data, just push it on
                // without doing any conversion. Otherwise, create a record.
                node = record;
                
                // This Reader may be configured to produce different model types based on
                // a differentiator field in the incoming data:
                // typeProperty name be a string, a function which yields the child type, or an object: {
                //     name: 'mtype',
                //     namespace: 'MyApp'
                // }
                if (typeProperty && (nodeType = me.getChildType(schema, node, typeProperty))) {

                    reader = nodeType.getProxy().getReader();

                    record = reader.extractRecord(node, readOptions, nodeType,
                                schema.hasAssociations(nodeType) && reader.getImplicitIncludes(),
                                reader.getFieldExtractorInfo(nodeType.fieldExtractors));
                } else {
                    record = me.extractRecord(node, readOptions, entityType, includes,
                                              fieldExtractorInfo);
                }

                if (record.isModel) {
                    // Trees need to be able to access the raw data (the XML node) in order to process its children.
                    record.raw = node;
                }
            }
            if (record.onLoad) {
                record.onLoad();
            }
            records[i] = record;
        }
        return records;
    },
});

**Comment by elmasse** [comment]
@yellenseram did you get a chance to try the cmd package? Let me know if you have any issue with that. BTW, is there any specific issue you solved with the code you posted?
