### ISSUE TITLE
How to dynamically switch language?

### ISSUE THREAD

**Issue by SumanBhowmick** [elmasse/Ext.i18n.Bundle#20]
Hi,

Is there any way I can switch between different languages at runtime??

Thanks In Advance.

**Comment by elmasse** [comment]
Hi @SumanBhowmick, sorry for the late response. There is an example in the pre-1.1 branch: https://github.com/elmasse/Ext.i18n.Bundle/tree/pre-1.1/examples/demo-classic-vm 
While it is not in the master branch and it's not published yet you can use that branch following the steps in the Readme to manually add the package. 
I haven't find the time yet to publish this new version but I'll do it as soon as I can.

**Comment by elmasse** [comment]
I just published a new version (1.1.0). It is available from the repository (See the README on how to add the repo to your Sencha Cmd). You can follow the example I mentioned in the previous comment.

I'm closing this issue. Please feel free to re-open it in case you have any questions.

**Comment by SumanBhowmick** [comment]
Hi,

My app is based on simple MVC architecture.

How do I change the language dynamically in the controller?

I find that the latest elmasse-bundle(version 1.1.0) examples are based on MVVM architecture.

Thanks In advance.
